services:
  api:
    container_name : api
    build:
      

      context: ./backend
      dockerfile: Dockerfile
    image: api-image:v1
    command: ["python", "main.py"]
    ports:
      - "8000:8000"
    networks:
      - api_network

  frontend:
    container_name : frontend
    build:
      
      context: ./frontend
      dockerfile: Dockerfile  
    image: frontend-image:v1
    command: ["npm", "run" , "dev"]
    ports:
      - "5173:5173"
    networks:
      - api_network
    depends_on:
      - api
  redis:
    container_name : redis
    image: redis:7-alpine
    restart : always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - api_network


volumes:
  redis-data:
    driver: local
networks:
  api_network:
    driver: bridge
